name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t tic_tac:latest .

      - name: Save Docker Image as Artifact
        run: |
          docker save -o tic_tac.tar tic_tac:latest

      - name: Upload Docker Image
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: tic_tac.tar

  code_health:
    name: Code Health Check
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Docker Image
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load Docker Image
        run: docker load -i tic_tac.tar

      - name: Run Linting (Inside Docker)
        run: |
          docker run --rm -v $(pwd):/app -w /app tic_tac:latest flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: code_health

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Docker Image
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load Docker Image
        run: docker load -i tic_tac.tar

      - name: Run Tests Inside Docker
        run: |
          docker run --rm tic_tac:latest pytest --junitxml=test-results.xml --cov=tic_tac

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: /app/test-results.xml